<?php

//Auto-generated by ArtaxServiceBuilder - https://github.com/Danack/ArtaxServiceBuilder
//
//Do not be surprised when any changes to this file are over-written.
//
namespace GithubService\Operation;

class listRepoCommits implements \ArtaxServiceBuilder\Operation {

    /**
     * @var $api \GithubService\GithubArtaxService\GithubArtaxService
     */
    public $api = null;

    /**
     * @var $api array
     */
    public $parameters = null;

    /**
     * @var $api \Artax\Response
     */
    public $response = null;

    /**
     * Get the last response.
     *
     * @return \Artax\Response
     */
    public function getResponse() {
        return $this->response;
    }

    /**
     * Set the last response. This should only be used by the API class when the
     * operation has been dispatched. Storing the response is required as some APIs
     * store out-of-bound information in the headers e.g. rate-limit info, pagination
     * that is not really part of the operation.
     */
    public function setResponse(\Artax\Response $response) {
        $this->response = $response;
    }

    public function __construct(\GithubService\GithubArtaxService\GithubArtaxService $api, $Authorization, $userAgent, $owner, $repo) {
        $defaultParams = [
            'Accept' => 'application/vnd.github.v3+json',
        ];
        $this->setParams($defaultParams);
        $this->api = $api;
        $this->parameters['Authorization'] = $Authorization;
        $this->parameters['userAgent'] = $userAgent;
        $this->parameters['owner'] = $owner;
        $this->parameters['repo'] = $repo;
    }

    public function setAPI(\GithubService\GithubArtaxService\GithubArtaxService $api) {
        $this->api = $api;
    }

    public function setParams(array $params) {
        if (array_key_exists('Accept', $params)) {
             $this->parameters['Accept'] = $params['Accept'];
        }
        if (array_key_exists('Authorization', $params)) {
             $this->parameters['Authorization'] = $params['Authorization'];
        }
        if (array_key_exists('userAgent', $params)) {
             $this->parameters['userAgent'] = $params['userAgent'];
        }
        if (array_key_exists('perPage', $params)) {
             $this->parameters['perPage'] = $params['perPage'];
        }
        if (array_key_exists('owner', $params)) {
             $this->parameters['owner'] = $params['owner'];
        }
        if (array_key_exists('repo', $params)) {
             $this->parameters['repo'] = $params['repo'];
        }
        if (array_key_exists('sha', $params)) {
             $this->parameters['sha'] = $params['sha'];
        }
        if (array_key_exists('path', $params)) {
             $this->parameters['path'] = $params['path'];
        }
        if (array_key_exists('author', $params)) {
             $this->parameters['author'] = $params['author'];
        }
        if (array_key_exists('since', $params)) {
             $this->parameters['since'] = $params['since'];
        }
        if (array_key_exists('until', $params)) {
             $this->parameters['until'] = $params['until'];
        }
    }

    public function setAccept($Accept) {
        $this->parameters['Accept'] = $Accept;
    }

    public function setAuthorization($Authorization) {
        $this->parameters['Authorization'] = $Authorization;
    }

    public function setUserAgent($userAgent) {
        $this->parameters['userAgent'] = $userAgent;
    }

    public function setPerPage($perPage) {
        $this->parameters['perPage'] = $perPage;
    }

    public function setOwner($owner) {
        $this->parameters['owner'] = $owner;
    }

    public function setRepo($repo) {
        $this->parameters['repo'] = $repo;
    }

    public function setSha($sha) {
        $this->parameters['sha'] = $sha;
    }

    public function setPath($path) {
        $this->parameters['path'] = $path;
    }

    public function setAuthor($author) {
        $this->parameters['author'] = $author;
    }

    public function setSince($since) {
        $this->parameters['since'] = $since;
    }

    public function setUntil($until) {
        $this->parameters['until'] = $until;
    }

    public function getParameters() {
        return $this->parameters;
    }

    /**
     * Apply any filters necessary to the parameter
     *
     * @return \GithubService\Model\Commits
     * @param string $name The name of the parameter to get.
     */
    public function getFilteredParameter($name) {
        if (array_key_exists($name, $this->parameters) == false) {
            throw new \Exception('Parameter '.$name.' does not exist.');
        }

        $value = $this->parameters[$name];

        switch ($name) {

            case ('Authorization'): {
                $args = [];
                $args[] = $value;
                $value = call_user_func_array('GithubService\Github::formatAuthToken', $args);
                break;
            }


            default:{}

        }

        return $value;
    }

    /**
     * Create an Artax\Request object from the operation.
     *
     * @return \Artax\Request
     */
    public function createRequest() {
        $request = new \Artax\Request();
        $url = null;
        $request->setMethod('GET');

        $queryParameters = [];

        if (array_key_exists('Accept', $this->parameters) == true) {
        $value = $this->getFilteredParameter('Accept');
           $request->setHeader('Accept', $value);
        }
        $value = $this->getFilteredParameter('Authorization');
        if ($value != null) {
            $request->setHeader('Authorization', $value);
        }
        $value = $this->getFilteredParameter('userAgent');
        $request->setHeader('User-Agent', $value);
        if (array_key_exists('perPage', $this->parameters) == true) {
        $value = $this->getFilteredParameter('perPage');
           $queryParameters['per_page'] = $value;
        }
        $value = $this->getFilteredParameter('owner');
        $queryParameters['owner'] = $value;
        $value = $this->getFilteredParameter('repo');
        $queryParameters['repo'] = $value;
        if (array_key_exists('sha', $this->parameters) == true) {
        $value = $this->getFilteredParameter('sha');
           $queryParameters['sha'] = $value;
        }
        if (array_key_exists('path', $this->parameters) == true) {
        $value = $this->getFilteredParameter('path');
           $queryParameters['path'] = $value;
        }
        if (array_key_exists('author', $this->parameters) == true) {
        $value = $this->getFilteredParameter('author');
           $queryParameters['author'] = $value;
        }
        if (array_key_exists('since', $this->parameters) == true) {
        $value = $this->getFilteredParameter('since');
           $queryParameters['since'] = $value;
        }
        if (array_key_exists('until', $this->parameters) == true) {
        $value = $this->getFilteredParameter('until');
           $queryParameters['until'] = $value;
        }

        //Parameters are parsed and set, lets prepare the request
        if ($url == null) {
            $url = "https://api.github.com/repos/{owner}/{repo}/commits";
        }
        $uriTemplate = new \ArtaxServiceBuilder\Service\UriTemplate\UriTemplate();
        $url = $uriTemplate->expand($url, $this->parameters);
        if (count($queryParameters)) {
            $url = $url.'?'.http_build_query($queryParameters, '', '&', PHP_QUERY_RFC3986);
        }
        $request->setUri($url);

        return $request;
    }

    /**
     * Create and execute the operation, returning the raw response from the server.
     *
     * @return \Artax\Response
     */
    public function createAndExecute() {
        $request = $this->createRequest();
        $response = $this->api->execute($request, $this);
        $this->response = $response;

        return $response;
    }

    /**
     * Create and execute the operation, then return the processed  response.
     *
     * @return mixed|\GithubService\Model\Commits
     */
    public function call() {
        $request = $this->createRequest();
        $response = $this->api->execute($request, $this);
        $this->response = $response;

        if ($this->shouldResponseBeProcessed($response)) {
            $instance = \GithubService\Model\Commits::createFromResponse($response, $this);

            return $instance;
        }
        return $response;
    }

    /**
     * Execute the operation, returning the parsed response
     *
     * @return \GithubService\Model\Commits
     */
    public function execute() {
        $request = $this->createRequest();
        return $this->dispatch($request);
    }

    /**
     * Execute the operation asynchronously, passing the parsed response to the
     * callback
     *
     * @return \GithubService\Model\Commits
     */
    public function executeAsync(callable $callable) {
        $request = $this->createRequest();
        return $this->dispatchAsync($request, $callable);
    }

    /**
     * Dispatch the request for this operation and process the response. Allows you to
     * modify the request before it is sent.
     *
     * @return \GithubService\Model\Commits
     * @param \Artax\Request $request The request to be processed
     */
    public function dispatch(\Artax\Request $request) {
        $response = $this->api->execute($request, $this);
        $this->response = $response;
        $instance = \GithubService\Model\Commits::createFromResponse($response, $this);

        return $instance;
    }

    /**
     * Dispatch the request for this operation and process the response asynchronously.
     * Allows you to modify the request before it is sent.
     *
     * @return \GithubService\Model\Commits
     * @param \Artax\Request $request The request to be processed
     * @param callable $callable The callable that processes the response
     */
    public function dispatchAsync(\Artax\Request $request, callable $callable) {
        return $this->api->executeAsync($request, $this, $callable);
    }

    /**
     * Dispatch the request for this operation and process the response. Allows you to
     * modify the request before it is sent.
     *
     * @return \GithubService\Model\Commits
     * @param \Artax\Response $response The HTTP response.
     */
    public function processResponse(\Artax\Response $response) {
        $instance = \GithubService\Model\Commits::createFromResponse($response, $this);

        return $instance;
    }

    /**
     * Determine whether the response is an error. Override this method to have a
     * per-operation decision, otherwise the function is the API class will be used.
     *
     * @return \GithubService\Model\Commits
     */
    public function isErrorResponse(\Artax\Response $response) {
        return $this->api->isErrorResponse($response);
    }

    /**
     * Determine whether the response should be processed. Override this method to have
     * a per-operation decision, otherwise the function is the API class will be used.
     *
     * @return \GithubService\Model\Commits
     */
    public function shouldResponseBeProcessed(\Artax\Response $response) {
        return $this->api->shouldResponseBeProcessed($response);
    }


}
