<?php

//Auto-generated by ArtaxServiceBuilder - https://github.com/Danack/ArtaxServiceBuilder
//
//Do not be surprised when any changes to this file are over-written.
//
namespace GithubService\Operation;

class updateAuthorization implements \ArtaxServiceBuilder\Operation {

    /**
     * @var \GithubService\GithubArtaxService\GithubArtaxService
     */
    public $api = null;

    /**
     * @var array
     */
    public $parameters = null;

    /**
     * @var \Amp\Artax\Response
     */
    public $response = null;

    /**
     * @var \Amp\Artax\Response
     */
    public $originalResponse = null;

    /**
     * Get the last response.
     *
     * @return \Amp\Artax\Response
     */
    public function getResponse() {
        return $this->response;
    }

    /**
     * Set the last response. This should only be used by the API class when the
     * operation has been dispatched. Storing the response is required as some APIs
     * store out-of-bound information in the headers e.g. rate-limit info, pagination
     * that is not really part of the operation.
     */
    public function setResponse(\Amp\Artax\Response $response) {
        $this->response = $response;
    }

    public function __construct(\GithubService\GithubArtaxService\GithubArtaxService $api, $scopes, $add_scopes, $remove_scopes, $note, $note_url, $fingerprint) {
        $this->api = $api;
        $this->parameters['scopes'] = $scopes;
        $this->parameters['add_scopes'] = $add_scopes;
        $this->parameters['remove_scopes'] = $remove_scopes;
        $this->parameters['note'] = $note;
        $this->parameters['note_url'] = $note_url;
        $this->parameters['fingerprint'] = $fingerprint;
    }

    public function setAPI(\GithubService\GithubArtaxService\GithubArtaxService $api) {
        $this->api = $api;
    }

    public function setParams(array $params) {
        if (array_key_exists('scopes', $params)) {
            $this->parameters['scopes'] = $params['scopes'];
        }
        if (array_key_exists('add_scopes', $params)) {
            $this->parameters['add_scopes'] = $params['add_scopes'];
        }
        if (array_key_exists('remove_scopes', $params)) {
            $this->parameters['remove_scopes'] = $params['remove_scopes'];
        }
        if (array_key_exists('note', $params)) {
            $this->parameters['note'] = $params['note'];
        }
        if (array_key_exists('note_url', $params)) {
            $this->parameters['note_url'] = $params['note_url'];
        }
        if (array_key_exists('fingerprint', $params)) {
            $this->parameters['fingerprint'] = $params['fingerprint'];
        }
    }

    /**
     * Set scopes
     *
     * Replaces the authorization scopes with these.
     *
     * @return $this
     */
    public function setScopes($scopes) {
        $this->parameters['scopes'] = $scopes;

        return $this;
    }

    /**
     * Set add_scopes
     *
     * A list of scopes to add to this authorization.
     *
     * @return $this
     */
    public function setAdd_scopes($add_scopes) {
        $this->parameters['add_scopes'] = $add_scopes;

        return $this;
    }

    /**
     * Set remove_scopes
     *
     * A list of scopes to remove from this authorization.
     *
     * @return $this
     */
    public function setRemove_scopes($remove_scopes) {
        $this->parameters['remove_scopes'] = $remove_scopes;

        return $this;
    }

    /**
     * Set note
     *
     * A note to remind you what the OAuth token is for.
     *
     * @return $this
     */
    public function setNote($note) {
        $this->parameters['note'] = $note;

        return $this;
    }

    /**
     * Set note_url
     *
     * A URL to remind you what app the OAuth token is for.
     *
     * @return $this
     */
    public function setNote_url($note_url) {
        $this->parameters['note_url'] = $note_url;

        return $this;
    }

    /**
     * Set fingerprint
     *
     * **This attribute is only available when using the
     * [mirage-preview](#deprecation-notice) media type.** A unique string to
     * distinguish an authorization from others created for the same client ID and
     * user.
     *
     * @return $this
     */
    public function setFingerprint($fingerprint) {
        $this->parameters['fingerprint'] = $fingerprint;

        return $this;
    }

    public function getParameters() {
        return $this->parameters;
    }

    /**
     * Apply any filters necessary to the parameter
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     * @param string $name The name of the parameter to get.
     */
    public function getFilteredParameter($name) {
        if (array_key_exists($name, $this->parameters) == false) {
            throw new \Exception('Parameter '.$name.' does not exist.');
        }

        $value = $this->parameters[$name];


        return $value;
    }

    /**
     * Create an Amp\Artax\Request object from the operation.
     *
     * @return \Amp\Artax\Request
     */
    public function createRequest() {
        $request = new \Amp\Artax\Request();
        $url = null;
        $request->setMethod('');


        $jsonParams = [];
        $value = $this->getFilteredParameter('scopes');
        $jsonParams['scopes'] = $value;
        $value = $this->getFilteredParameter('add_scopes');
        $jsonParams['add_scopes'] = $value;
        $value = $this->getFilteredParameter('remove_scopes');
        $jsonParams['remove_scopes'] = $value;
        $value = $this->getFilteredParameter('note');
        $jsonParams['note'] = $value;
        $value = $this->getFilteredParameter('note_url');
        $jsonParams['note_url'] = $value;
        $value = $this->getFilteredParameter('fingerprint');
        $jsonParams['fingerprint'] = $value;

        //Parameters are parsed and set, lets prepare the request
        if (count($jsonParams)) {
            $jsonBody = json_encode($jsonParams);
            $request->setHeader("Content-Type", "application/json");
            $request->setBody($jsonBody);
        }
        if ($url == null) {
            $url = "https://api.github.com/authorizations/{id}";
        }
        $request->setUri($url);

        return $request;
    }

    /**
     * Create and execute the operation, returning the raw response from the server.
     *
     * @return \Amp\Artax\Response
     */
    public function createAndExecute() {
        $request = $this->createRequest();
        $response = $this->api->execute($request, $this);
        $this->response = $response;

        return $response;
    }

    /**
     * Create and execute the operation, then return the processed  response.
     *
     * @return mixed|\GithubService\Model\GithubService\Model\OauthAccess
     */
    public function call() {
        $request = $this->createRequest();
        $response = $this->api->execute($request, $this);
        $this->response = $response;

        if ($this->shouldResponseBeProcessed($response)) {
            $instance = \GithubService\Model\GithubService\Model\OauthAccess::createFromResponse($response, $this);

            return $instance;
        }
        return $response;
    }

    /**
     * Execute the operation, returning the parsed response
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     */
    public function execute() {
        $request = $this->createRequest();
        return $this->dispatch($request);
    }

    /**
     * Execute the operation asynchronously, passing the parsed response to the
     * callback
     *
     * @return \Amp\Promise
     */
    public function executeAsync(callable $callable) {
        $request = $this->createRequest();
        return $this->dispatchAsync($request, $callable);
    }

    /**
     * Dispatch the request for this operation and process the response. Allows you to
     * modify the request before it is sent.
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     * @param \Amp\Artax\Request $request The request to be processed
     */
    public function dispatch(\Amp\Artax\Request $request) {
        $response = $this->api->execute($request, $this);
        $this->response = $response;
        $instance = \GithubService\Model\GithubService\Model\OauthAccess::createFromResponse($response, $this);

        return $instance;
    }

    /**
     * Dispatch the request for this operation and process the response asynchronously.
     * Allows you to modify the request before it is sent.
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     * @param \Amp\Artax\Request $request The request to be processed
     * @param callable $callable The callable that processes the response
     */
    public function dispatchAsync(\Amp\Artax\Request $request, callable $callable) {
        return $this->api->executeAsync($request, $this, $callable);
    }

    /**
     * Dispatch the request for this operation and process the response. Allows you to
     * modify the request before it is sent.
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     * @param \Amp\Artax\Response $response The HTTP response.
     */
    public function processResponse(\Amp\Artax\Response $response) {
        $instance = \GithubService\Model\GithubService\Model\OauthAccess::createFromResponse($response, $this);

        return $instance;
    }

    /**
     * Determine whether the response should be processed. Override this method to have
     * a per-operation decision, otherwise the function is the API class will be used.
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     */
    public function shouldResponseBeProcessed(\Amp\Artax\Response $response) {
        return $this->api->shouldResponseBeProcessed($response);
    }

    /**
     * Determine whether the response is an error. Override this method to have a
     * per-operation decision, otherwise the function from the API class will be used.
     *
     * @return null|\ArtaxServiceBuilder\BadResponseException
     */
    public function translateResponseToException(\Amp\Artax\Response $response) {
        return $this->api->translateResponseToException($response);
    }

    /**
     * Determine whether the response indicates that we should use a cached response.
     * Override this method to have a per-operation decision, otherwise the
     * functionfrom the API class will be used.
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     */
    public function shouldUseCachedResponse(\Amp\Artax\Response $response) {
        return $this->api->shouldUseCachedResponse($response);
    }

    /**
     * Determine whether the response should be cached. Override this method to have a
     * per-operation decision, otherwise the function from the API class will be used.
     *
     * @return \GithubService\Model\GithubService\Model\OauthAccess
     */
    public function shouldResponseBeCached(\Amp\Artax\Response $response) {
        return $this->api->shouldResponseBeCached($response);
    }

    /**
     * Set the original response. This may be different from the cached response if one
     * is used.
     */
    public function setOriginalResponse(\Amp\Artax\Response $response) {
        $this->originalResponse = $response;
    }

    /**
     * Get the original response. This may be different from the cached response if one
     * is used.
     *
     * @return \Amp\Artax\Response
     */
    public function getOriginalResponse() {
        return $this->originalResponse;
    }


}
